#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)

while IFS= read -r url; do
    curl \
        -H "Accept: application/json" \
        -H "Authorization: LOW $IA_API_KEY" \
        -d "capture_all=0" \
        -d "capture_outlinks=1" \
        -d "capture_screenshot=1" \
        -d "js_behavior_timeout=30" \
        -d "url=$url" \
        --retry 10 \
        --retry-delay 10 \
        --retry-all-errors \
        --no-progress-meter \
        https://web.archive.org/save | jq
    sleep 10
done < /dev/stdin
