#!/usr/bin/env node

const readline = require("readline");

const rl = readline.createInterface({
  input: process.stdin,
});

rl.on("line", (line) => {
  for (let i of line.split("\n")) {
    let uri = encodeURI(i)
      .replaceAll(encodeURI("["), "[")
      .replaceAll(encodeURI("]"), "]")
      .replaceAll(encodeURI("{"), "{")
      .replaceAll(encodeURI("}"), "}")
      .replaceAll(
        "SEARCH_TERMS",
        `{${[
          "筧礼",
          "江口慶",
          "大野遥斗",
          "渡辺大馳",
          "稲毛眞生",
          "フクチッチ",
          "勅使河原空",
          "松尾そのま",
          "天才てれびくん",
          "天てれ",
          "新井琉月",
          "小久保向一朗",
          "丸山煌翔",
          "盛武美音",
          "池村咲良",
          "香月萌衣",
          "今野斗葵",
          "大野冴姫",
          "金児莉良",
          "シェパード龍アーサー",
          "ポン璃菜アメリー",
          "廣末裕理",
          "ティモンディ",
          "ギュナイ滝美",
        ]
          .map((e) => encodeURI(e))
          .join(",")}}`
      )

      .replaceAll(
        "INSTAGRAM_SCREEN_NAMES",
        `{${[
          "arthur_0524_",
          "daichi_watanabe0606",
          "haruto_ohno_official",
          "himawari_aozorae",
          "i.am.mariaaaa",
          "lilala_58",
          "lina.amelie_pont_official",
          "maeda_timon_d",
          "mauna_inage_official",
          "mio.mioim.oim",
          "rei_kakehi",
          "saki_ohno_sign",
          "sonia_sonisoni",
          "sonopy526",
          "sora.chocolate",
          "toa_konno1103",
          "yuma_sakagami",
        ].join(",")}}`
      )
      .replaceAll(
        "TWITTER_SCREEN_NAMES",
        `{${[
          "CurryRice_41",
          "i6Ma5WhgFUKgHFY",
          "ToA_Konno1103",
          "msonopy526",
          "saki_ohno",
          "sakura_ikemura",
          "sora_hello0526",
        ].join(",")}}`
      );
    process.stdout.write(uri + "\n");
  }
});
