name: "Scheduled cURLs #1"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  curl-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update curl
        run: |
          sudo apt update
          sudo apt install -y jq

      - name: Percent-encode non-ASCII characters in target URLs
        run: ./generate

      - name: Request archiving of target URLs
        env:
          IA_API_KEY: ${{ secrets.IA_API_KEY }}
        run: cat target-1.temp | xargs ./archive
