name: Scheduled cURLs (priority)

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Percent-encode non-ASCII characters in target URLs
        run: |
          ROOT=$(git rev-parse --show-toplevel)
          cat $ROOT/target_priority | node $ROOT/process.js > $ROOT/target_priority_processed
      - name: Request archiving of target URLs
        run: xargs -I {} curl -fIvsS {} > /dev/null < $(git rev-parse --show-toplevel)/target_priority_processed
