name: "Scheduled cURLs #3"

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  curl-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          git clone https://github.com/227274/curl.git custom-curl --depth 1
          cd custom-curl
          autoreconf -fi
          ./configure --with-openssl
          make
          sudo make install
          sudo apt-get update
          sudo apt-get reinstall -y \
            jq \
            libcurl4

      - name: Percent-encode non-ASCII characters in target URLs
        run: ./generate

      - name: Request archiving of target URLs
        env:
          IA_API_KEY: ${{ secrets.IA_API_KEY }}
        run: cat target-3.temp | xargs ./archive
