name: Scheduled cURLs

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Percent-encode non-ASCII characters in target URLs
        run: |
          ROOT=$(git rev-parse --show-toplevel)
          cat $ROOT/target | $ROOT/process > $ROOT/target.temp
      - name: Request archiving of target URLs
        run: xargs -I {} curl --retry 1 --retry-delay 60 --retry-connrefused -IvsS {} > /dev/null < $(git rev-parse --show-toplevel)/target.temp
